# coding=utf-8
# author :veronica_ry
from py2neo import Graph, Node, Relationship
test_graph = Graph("http://127.0.0.1:7474/browser/", username="neo4j", password="08166517416reny")
test_graph.delete_all()

teacher1 = Node("老师", name="老师1")
teacher2 = Node("老师", name="老师2")
stu1 = Node("学生", name="学生1")
stu2 = Node("学生", name="学生2")
stu3 = Node("学生", name="学生3")
stu4 = Node("学生", name="学生4")
pro1 = Node("项目", name="项目1")
pro2 = Node("项目", name="项目2")
test_graph.create(teacher1)
test_graph.create(teacher2)
test_graph.create(stu1)
test_graph.create(stu2)
test_graph.create(stu3)
test_graph.create(stu4)
test_graph.create(pro1)
test_graph.create(pro2)

teacher1_mentor_stu1 = Relationship(teacher1, "师生", stu1)
teacher1_mentor_stu2 = Relationship(teacher1, "师生", stu2)
teacher2_mentor_stu3 = Relationship(teacher2, "师生", stu3)
teacher2_mentor_stu4 = Relationship(teacher2, "师生", stu4)
test_graph.create(teacher1_mentor_stu1)
test_graph.create(teacher1_mentor_stu2)
test_graph.create(teacher2_mentor_stu3)
test_graph.create(teacher2_mentor_stu4)

teacher1_re_pro1 = Relationship(teacher1, "负责人", pro1)
teacher1_re_pro2 = Relationship(teacher1, "成员", pro2)
teacher2_re_pro1 = Relationship(teacher2, "成员", pro1)
teacher2_re_pro2 = Relationship(teacher2, "负责人", pro2)
test_graph.create(teacher1_re_pro1)
test_graph.create(teacher1_re_pro2)
test_graph.create(teacher2_re_pro1)
test_graph.create(teacher2_re_pro2)

stu1_re_pro1 = Relationship(stu1, "成员", pro1)
stu1_re_pro2 = Relationship(stu1, "成员", pro2)
stu2_re_pro1 = Relationship(stu2, "成员", pro1)
stu2_re_pro2 = Relationship(stu2, "成员", pro2)
stu3_re_pro1 = Relationship(stu3, "成员", pro1)
stu3_re_pro2 = Relationship(stu3, "成员", pro2)
stu4_re_pro1 = Relationship(stu4, "成员", pro1)
stu4_re_pro2 = Relationship(stu4, "成员", pro2)
test_graph.create(stu1_re_pro1)
test_graph.create(stu1_re_pro2)
test_graph.create(stu2_re_pro1)
test_graph.create(stu2_re_pro2)
test_graph.create(stu3_re_pro1)
test_graph.create(stu3_re_pro2)
test_graph.create(stu4_re_pro1)
test_graph.create(stu4_re_pro2)